[RSpec編] 04_未完成のテストコード修正
kazuki13070311/rspec_app_exam pull request #1
Opened 2021-01-18 10:09 UTC by kazuki13070311

## TODO
 
・ローカル変数ではなく let を使用する①
（テスト内容： ステータスを完了にした場合、Taskの完了日に今日の日付が登録されること）

・ローカル変数ではなく let を使用する②
（テスト内容： Taskが新規作成されること）

・ローカル変数ではなく let を使用する③
（テスト内容： Taskが表示されること）
 
・ローカル変数ではなく let を使用する④
（テスト内容： ステータスを完了にした場合、Taskの完了日に今日の日付が登録されること）

・FactoryBotのtraitを利用する
（テスト内容： 既にステータスが完了のタスクのステータスを変更した場合、Taskの完了日が更新されないこと）

## FIXME

下記テストケースの修正
・Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること
・Taskを編集した場合、一覧画面で編集後の内容が表示されること
・Taskが削除されること

2021-01-18 10:35 UTC, yuji91 requested changes
3点コメントしました！

2021-01-18 10:35 UTC, yuji91 commented on spec/system/task_spec.rb
> +    let(:task) { create(:task) }
1つ上の階層に定義していれば、各describeで定義する必要はなくなりますね。

2021-01-18 10:35 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%m/%d %H:%M').to_i)
NG例のPRを確認して欲しいのですが、このstrftimeの引数の値を変える修正方法には問題があります。

2021-01-18 10:35 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to have_content "Task was successfully destroyed."
こちらは何が原因でテストが失敗していて、どのように修正したか説明できますでしょうか。
また本来のテストケースではどのような内容を確認しようとしているかも意識して欲しいです。

2021-01-18 11:29 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +    let(:task) { create(:task) }
f9d7b09 letで作成しているFactoryBotを1つ上の階層へ上げてリファクタリングを行いました

2021-01-18 11:30 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%m/%d %H:%M').to_i)
e2504f4 strftimeの引数の値を変える修正方法を修正しました（日付表示を左詰め寄せにする）

2021-01-18 11:43 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        expect(page).to have_content "Task was successfully destroyed."
### 修正した手順

1. `expect(page).not_to have_content task.title`でtaskのtitleがないことを期待していましたが、task.titleがあるとRSpec側が判定したので、byebugを使用して投稿はできているか？投稿の削除はできているか？の確認を行いました。

2. 投稿と削除は正常にできていました。
3. 投稿と削除はできているにも関わらず`expect(page).not_to have_content task.title`で「task.title」が存在すると判定されていたので、`expect(page).not_to have_content task.title`の記述が間違っているのではと考えました。
4. taskが削除されているかどうかを判定するテストだと思いましたので、taskが削除されたということが分かれば良いかと思い、削除された時に表示されるflashメッセージ「Task was successfully destroyed.」が表示されているかどうかの判定（`expect(page).to have_content "Task was successfully destroyed."`）にテスト内容を修正しました。

2021-01-18 12:35 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%m/%d %H:%M').to_i)
NG例のPullRequestで指摘を受けている修正方法とほとんど同様の内容となっています。
https://gyazo.com/8c7e781588ce43d6b481cb418dd8bc04

「view側で使用しているメソッドを呼び出す形」に対応をお願いします。

2021-01-18 12:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to have_content "Task was successfully destroyed."
flashメッセージの判定には、以下のような問題があります。
1. 複数件からのタスクデータ削除のテストケースにおいて、削除対象以外を誤って削除されてもテストが通ってしまう。
2. flashメッセージとテストケースに依存性が出来てしまい、メッセージが変わるとテストが失敗する。

こちらも失敗例のPullRequestでの指摘事項をヒントに対応をお願いします。
[![Image from Gyazo](https://i.gyazo.com/9f6478652883c2bd42f6cdb751f33bfd.png)](https://gyazo.com/9f6478652883c2bd42f6cdb751f33bfd)

2021-01-18 12:39 UTC, yuji91 requested changes
1点の修正を確認しました。
2点、引き続き対応をお願いします。

2021-01-18 14:54 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%m/%d %H:%M').to_i)
6ddd05f view側で使用しているメソッドを呼び出す形に修正

2021-01-18 15:00 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        expect(page).to have_content "Task was successfully destroyed."
### ・flashメッセージの問題点1に関して
検証テストする画面で、削除対象外のものを削除した際にも削除対象を削除した時と同じflashメッセージが出てしまい、テストが間違って通ってしまうということなんですね。勉強になりました。

### ・flashメッセージの問題点2に関して
「flashメッセージとテストケースに依存性が出来てしまう」というのは、flashメッセージかテストケースのどちらか片方の内容を変更すると、もう一方の方も同じように変更しなければならなくなるから非効率で間違いやすいという解釈であっていますでしょうか？

2021-01-18 15:00 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        expect(page).to have_content "Task was successfully destroyed."
2d653c7 classを指定して特定の要素を検証できるよう修正

2021-01-19 02:30 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to have_content "Task was successfully destroyed."
> flashメッセージかテストケースのどちらか片方の内容を変更すると、もう一方の方も同じように変更しなければならなくなる

はい。この認識は合っています。

> 非効率で間違いやすい

非効率というよりは「テストケースが実装の変更に弱く、メンテナンスコストが高い書き方になっている。」という認識ですね。依存性がなければ、flashメッセージを変更してもテストは失敗しないので、テストの信頼性がありflashメッセージの変更も気兼ねなく実施できます。

2021-01-19 02:35 UTC, yuji91 requested changes
修正について問題ありません。

細かい点をいくつか追加で指摘したので、ご確認をお願いします。

2021-01-19 02:35 UTC, yuji91 commented on spec/system/task_spec.rb
> +    let(:task_done) { create(:task, :done) }
恐らく1つ上の階層で定義しているので不要になるかと思います。

2021-01-19 02:35 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id)
letを定義しているので、ローカル変数に代入する形で宣言しなくても良いと思います。

` visit project_tasks_path(project)`の行でprojectのletが実行され、
`expect(find('.task_list')).not_to have_content task.title`の行でtaskのletが実行される想定です。

2021-01-19 02:35 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(short_time(task.reload.deadline))
修正方法は問題ありません。
もともとTime.currentで実装されていたので、short_timeの引数は変えなくても良いかもしれません。

2021-01-19 02:35 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id)
letの定義により、ローカル変数に代入する形でのテストデータの宣言は不要になるかと思われます。

2021-01-19 10:12 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        expect(page).to have_content "Task was successfully destroyed."
なるほど、運用していく上でのメンテナンスを考えた時に、メンテナンスコストが高くなってしまう。要は依存性があると、1つを修正するともう1つも修正しないといけなくなるので、手間が増えてしまうということですね。
ありがとうございます。よく理解できました！

2021-01-19 10:38 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +    let(:task_done) { create(:task, :done) }
d4c2aec 不要なコードの削除

2021-01-19 10:38 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id)
7fb271e リファクタリングを行いました

2021-01-19 10:39 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id)
e1a86c5 不要なコードを削除

2021-01-19 10:51 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(short_time(task.reload.deadline))
short_timeの引数を元に戻してテストしてみたところエラーが出てしまい、
再度ご指摘前の`have_content(short_time(task.reload.deadline))`に戻しました。
short_timeの引数を変えなくても良いかもしれないというのは、view側と全く同じ引数で良いという事でしょうか？それともApplicationHelperでメソッドで定義している`short_time(datetime)`にするという意味でしょうか？
恐れ入りますが、ご教授していただけると助かります。

2021-01-19 12:34 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(short_time(task.reload.deadline))
> short_timeの引数を元に戻す

元に戻すというより`short_time(TIme.current)`で動くと思うので、`task.reload.deadline`の値を指定しなくても良いかと思いました。

`task.reload.deadline`でもタスクに登録された期限の値が取得できるので、こちらその形式でも大丈夫です！

2021-01-19 12:38 UTC, yuji91 requested changes
細かい点ですが指摘しました。

レビュー依頼前に全体的にコード差分に問題ないかを確認すると、開発現場でレビュー依頼をする際に抜け漏れが防止できるので良いと思います。
https://github.com/kazuki13070311/rspec_app_exam/pull/1/files

2021-01-19 12:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id)
この部分も省略できるかと思います。

2021-01-19 12:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +      it 'ステータスを完了にした場合、Taskの完了日に今日の日 付が登録されること' do
スペースが入ってしまっていますね。

2021-01-19 12:52 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(short_time(task.reload.deadline))
なるほどですね！理解しました！
ご教授ありがとうございます。

2021-01-19 13:00 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +      it 'ステータスを完了にした場合、Taskの完了日に今日の日 付が登録されること' do
d652e53 余分なスペースを修正

2021-01-19 13:05 UTC, kazuki13070311 commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id)
e148948 不要なコードを削除（間違えてコメントアウトの状態でpushしてしまい、その後コメントアウト部分を削除して再度pushしたのですが、git commitの内容が更新されませんでした…）

2021-01-19 14:36 UTC, yuji91 approved these changes
LGTMです！

慣れるまでは`git status`でのコミット対象ファイルの確認や、レビュー依頼時にコード差分のセルフチェックなどは習慣付けておくと良いと思います！

2021-01-19 22:35 UTC, merged